### ISSUE TITLE
[BUG] - key event for ctrl shift char is not working.

### ISSUE THREAD

**Issue by tramhao** [veeso/tui-realm#47]
## Description
I set key binding for ctrl, alt, ctl+alt works. but as long as shift is involved, char doesn't work.
## Steps to reproduce

ctrl+shift+special keys like left, pagedown works. but char doesn't work.  when bits is 3, char doesn‘’t work. I tried different computers and same problem.

## Expected behaviour

It's supposed to work like other keys.

## Environment

- OS: arch
- Architecture  x86_64
- Rust version stable
- tui-realm version most recent.

**Comment by tramhao** [comment]
```toml
[keys.global_quit.code]
type = "Char"
args = "q"

[keys.global_quit.modifier]
type = "KeyModifiers"
bits = 0
```
For example, above config works, but when I change bits to 3,5,7, and char to `Q`, it doesn't work. When bits is 1, and char is `Q`, it works. It's really strange. When bits is 2 or 4, char is `q`, it works without problem. 
I tried alacritty and kitty. I checked the possible conflict key in alacritty and there is no conflict. I change q to e or r, it's the same effect.
